Passes all test cases in JupyterNotebook
BirkhoffG/jax-practice pull request #1
Opened 2023-10-20 19:43 UTC by FirdausChoudhury

2023-10-20 20:09 UTC, BirkhoffG commented
Can you run `nbdev_export` and `nbdev_clean`, and commit again?

2023-10-20 20:20 UTC, FirdausChoudhury commented
<p>Ran them and commited</p>

2023-10-21 00:34 UTC, BirkhoffG commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<pre class="ql-syntax" spellcheck="false">Line #9.            if self.min_ == self.max_:
</pre><p>In general, to prevent the denominator is close to 0, what we can do is to add a small number in the denominator (e.g., 1e-5).</p><p> </p><p>Writing <code>if</code> might not prevent corner cases. If  self.min_ = self.max_ + 1e-6, sometimes it might also lead to error, because the denominator is close to 0, and get round to 0.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/BirkhoffG/jax-practice/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2023-10-21 00:34 UTC, BirkhoffG commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<pre class="ql-syntax" spellcheck="false">Line #13.            encoder = skp.OneHotEncoder(sparse_output=False)
</pre><p>This is not wrong, but could you write the <code>OneHotEncoder</code>  without using sklearn? Please rewrite the transform/inverse_transform functions here.</p><p> </p><p>Hint: check <code>jax.nn.one_hot</code>  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/BirkhoffG/jax-practice/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2023-10-21 00:34 UTC, BirkhoffG commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<pre class="ql-syntax" spellcheck="false">Line #25.                    xs = xs.astype(np.float64)
</pre><p>I would simply write <code>xs = xs.astype(xs.dtype)</code>. No need for an <code>if</code>   satetment.  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/BirkhoffG/jax-practice/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2023-10-21 00:34 UTC, BirkhoffG commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<pre class="ql-syntax" spellcheck="false">Line #9.            for feature in self.features:
</pre><p>This is correct, but you can write it more concise by using <code>enumerate</code> </p><p> </p><p><code></code><code>python</p><p>for i, feature in enumerate(self.features):</p><p>    ...</p><p></code><code></code> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/BirkhoffG/jax-practice/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2023-10-21 00:39 UTC, BirkhoffG commented
@FirdausChoudhury Thanks for your PR. Could you make changes based on my comments above?

In addition, you have deleted many of the `#| export` directives. This directive label the block to be exported to `jax_practice/data_preprocessor.py`, so that we can use code written in the jupyter notebook.

After making these changes, please run `nbdev_export` and `nbdev_clean` before commit.

2023-10-21 00:40 UTC, BirkhoffG requested changes
Thanks for your PR. Could you make changes based on my comments above?

In addition, you have deleted many of the `#| export` directives. This directive label the block to be exported to `jax_practice/data_preprocessor.py`, so that we can use code written in the jupyter notebook.

After making these changes, please run `nbdev_export` and `nbdev_clean` before commit.

2023-10-21 02:32 UTC, FirdausChoudhury commented
<p>Thanks for the feedback. I'll get them implemented and commit them</p>

2023-10-22 17:46 UTC, FirdausChoudhury commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<p>change completed</p>

2023-10-26 15:23 UTC, FirdausChoudhury commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<p>resolved</p>

2023-10-27 10:52 UTC, FirdausChoudhury commented on nbs/00_data_preprocessor.ipynb
>     "metadata": {},
<p>Completed</p>

2023-10-29 22:40 UTC, BirkhoffG commented
Good work @FirdausChoudhury. I think no further comments.

You have successfully completed this task. Congratulations!

2023-10-29 22:40 UTC, closed without merging